// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gknljryxosrbuokseouj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imdrbmxqcnl4b3NyYnVva3Nlb3VqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQzNTgzNTgsImV4cCI6MjA2OTkzNDM1OH0.NY-yyos4JN48swChRlrowiqOyDDpdCX-cRVYVC02hc8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});